# Generated by Django 4.1.6 on 2023-02-05 17:26

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('position', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, default='', upload_to='profile')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('maiden', models.CharField(blank=True, max_length=50, null=True)),
                ('surname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=10)),
                ('id_number', models.CharField(max_length=14)),
                ('status', models.CharField(blank=True, default='', max_length=50)),
                ('created', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('debtor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.debtor')),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('first_payment', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('second_payment', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('final_payment', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_fully_paid', models.CharField(blank=True, default='no', max_length=50, null=True)),
                ('first_payment_due_date', models.DateField(default=datetime.date(2023, 3, 7), null=True)),
                ('second_payment_due_date', models.DateField(default=datetime.date(2023, 4, 6), null=True)),
                ('final_payment_due_date', models.DateField(default=datetime.date(2023, 5, 6), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('debtor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.debtor')),
                ('product', models.CharField(max_length=50)),
                ('product_serial_no', models.CharField(max_length=50)),
                ('product_selling_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('product_details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('debtor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.debtor')),
                ('employer', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('employer_contact', models.CharField(max_length=50)),
            ],
        ),
    ]
