# Generated by Django 4.1.6 on 2023-02-06 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='final_payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='final_payment_due_date',
            field=models.DateField(default=datetime.date(2023, 5, 7), null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='first_payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='first_payment_due_date',
            field=models.DateField(default=datetime.date(2023, 3, 8), null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='second_payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='second_payment_due_date',
            field=models.DateField(default=datetime.date(2023, 4, 7), null=True),
        ),
    ]
